### ISSUE TITLE
`lein umlaut dot` may be doing too much

### ISSUE THREAD

**Issue by luchiniatwork** [workco/lein-umlaut#7]
Here's the scenario: I wanted to increase the resolution of the generated `png`.

It turns out that GraphViz supports a `dpi` settings that can either be set when running the `dot` command line via `-Gdpi=300` or a property of the graph such as:

```
graph G { 
  graph [ dpi = 300 ]; 
  /* The rest of your graph here. */ 
}
```

Neither way is possible when using `lein umlaut dot` because it encapsulates maybe a bit too much.

The alternatives here are either open up `lein umlaut dot` to support args to be sent to `dot` (a bit convoluted) or having `lein umlaut dot` generate the dot file on stdout while a new `lein umlaut png` would save the file.

Thoughts?

**Comment by nmoya** [comment]
This was closed by: https://github.com/workco/lein-umlaut/pull/8
